In [1]:
import numpy as np


In [8]:
import numpy as np


def tune_observation_view(observation, player_id):
    '''
    player_id either 1 or -1. Swap the observation such that 1 means self and -1 means the opponent 
    e.g. 
    if player_id = 1, no need to swap the view,
    input = array([1, -1, 0,
                   0, 0, 0,
                   -1, -1, 1])
           
    output = array([1, -1, 0,
                    0, 0, 0,
                    -1, -1, 1])
                    
    if player_id = -1, need to swap the view,
    input = array([1, -1, 0,
                   0, 0, 0,
                   -1, -1, 1])
           
    output = array([-1, 1, 0,
                    0, 0, 0,
                    1, 1, -1])
    
    '''
    return observation * player_id

if True:
    observation = np.array([1, -1, 0,
                           0, 0, 0,
                           -1, -1, 1])
    a = tune_observation_view(observation, -1)
    
    print(observation)
    print(a)

[ 1 -1  0  0  0  0 -1 -1  1]
[-1  1  0  0  0  0  1  1 -1]


In [4]:
def process_memory(memory, is_terminal_state):
    if (len(memory) == memory_size + 1) and (is_terminal_state):
        # special handle
        pass
    
    # do all the shifting 
    for each record:
        if player is 2:
            swap observation, next_observation, reward
        
    pass

SyntaxError: invalid syntax (<ipython-input-4-ab283bd9a1f2>, line 7)

In [5]:
memory = np.array([])

next_observation, player_turn, reward, is_terminal_state = env.step(action)
memory.append([original_observation, action, reward, next_observation, player])

if (len(memory) == memory_size + 1) or (is_terminal_state):
    # shift reward, state, done, and assign 1 for my round and 2 for the opponent round
    memory_for_training = process_memory(memory, is_terminal_state)
    if is_terminal_state:
        memory = np.array([])
    else:
        memory = memory[-1]
        
    agent.learn(memory_for_training)

NameError: name 'env' is not defined

In [ ]:
# main flow

load_weight_path = 'dummy_path'
model_weight_path = 'dummy_path'

env = make_env()
bot1 = Bot(load_weight_path)
bot2 = Bot()
bot_list = [bot1, bot2]
unprocess_memory = np.array([])

num_episode = 10


for episode in range(num_episode):
    env.reset()
    
    # get initial state
    observation, player_turn, reward, is_terminal_state = env.get_current_info()
    
    while not is_terminal_state:
        # if now is player 2's turn, swap the observation
        if player_turn == 2:
            swapped_observation = swap_observation_view(observation)
            action = bot_list[player_turn-1].select_action(swapped_observation)
        elif player_turn == 1:
            action = bot_list[player_turn-1].select_action(observation)
        else:
            print('Error in player turn. Current player turn is %s.\n' % player_turn)
        
        next_observation, next_player_turn, reward, is_terminal_state = env.step(action)
        
        unprocess_memory.append([observation, action, reward, next_observation, player_turn])
        
        if (len(unprocess_memory) == memory_size + 1) or (is_terminal_state):
            # shift reward, state, done, and assign 1 for my round and 2 for the opponent round
            memory_for_training = process_memory(unprocess_memory, is_terminal_state)
            if is_terminal_state:
                unprocess_memory = np.array([])
            else:
                unprocess_memory = unprocess_memory[-1]

            bot1.learn(memory_for_training)
            
        observation, player_turn = next_observation, next_player_turn
        
    # save the model weight periodically
    if (episode + 1) % 50 == 0:
        bot1.save_weight(model_weight_path)

In [ ]:
class Bot():
    def __init__(self, load_weight_path=None):
        self.observation['board'] = np.zeros([9, 3])
        self.observation['1p_inventory'] = np.array([2, 2, 2])
        self.observation['2p_inventory'] = np.array([2, 2, 2])
                
        self.model = self.build_model()
        if load_weight_path is not None:
            self.model = self.load_weight()
        
        self
        pass
    
    def build_model(self):
        pass
    
    def load_model(self):
        pass
    
    def choose_action(self, observation):
        pass

In [ ]:
bot1 = Bot()
bot2 = Bot()

player_list = [bot1, bot2]
save_list = []

for episode in range(100):
    # reset environment
    env.reset()
    
    # start from the 1st player
    player_turn = 1
    observation = env.observation
    while game not end:
        action = player_list[state['player_turn']].pick_action(observation)
        
        # if the action is not valid, the program will be break      
        state, next_observation, reward = env.step(action)
        
        save_list.append([observation, action, next_observation, reward])
        observation = next_observation
        

        
        

In [4]:
board = np.zeros([9, 3])
np.zeros(3)

array([0., 0., 0.])

In [6]:
temp = np.array([1,2,3,4,5,6,7,8,9])

array([2, 4, 6])

In [9]:
if not None:
    print('Hi')

Hi
