In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from py_files.board import Board
from py_files.player import Q_player, Random_player, Human

import numpy as np

Using TensorFlow backend.


In [3]:
p1_config = {'player_type':'q_player', 'hidden_layers_size':[20,10]}
p2_config = {'player_type':'random', 'hidden_layers_size':[20,10,10]}

win_reward = 1
lose_reward = -1
draw_reward = 0

test_board = Board(p1_config=p1_config, p2_config=p2_config, 
                   win_reward=win_reward, lose_reward=lose_reward, 
                   draw_reward=draw_reward)

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


In [4]:
episode = 100000

test_board.train(episode)

Current episode: 0
Loss: 0
p1 win rate: 0.0
p1 draw rate: 0.0
p1 lose rate: 0.0

0.9980014995000627
Instructions for updating:
Use tf.cast instead.
0.3839513873773329
Current episode: 1000
Loss: 0.04260074719786644
p1 win rate: 0.488
p1 draw rate: 0.107
p1 lose rate: 0.405

0.15560023529537093
0.06649172827376076
Current episode: 2000
Loss: 0.035193562507629395
p1 win rate: 0.665
p1 draw rate: 0.048
p1 lose rate: 0.287

0.028215267485108404
0.0119609677415489
Current episode: 3000
Loss: 0.03105000965297222
p1 win rate: 0.683
p1 draw rate: 0.054
p1 lose rate: 0.263

0.01
0.01
Current episode: 4000
Loss: 0.05891755223274231
p1 win rate: 0.69
p1 draw rate: 0.048
p1 lose rate: 0.262

0.01
0.01
Current episode: 5000
Loss: 0.03744461387395859
p1 win rate: 0.72
p1 draw rate: 0.038
p1 lose rate: 0.242

0.01
0.01
Current episode: 6000
Loss: 0.04688749089837074
p1 win rate: 0.729
p1 draw rate: 0.038
p1 lose rate: 0.233

0.01
0.01
Current episode: 7000
Loss: 0.02548997849225998
p1 win rate: 0.717

KeyboardInterrupt: 

In [5]:
p1 = test_board.get_player(1)

In [6]:
memory = p1.memory
p1.memory.memory

deque([[array([ 0.,  0., -1., -1., -1.,  0.,  1.,  0.,  1.]),
        1,
        -1,
        array([ 0.,  1., -1., -1., -1., -1.,  1.,  0.,  1.]),
        True],
       [array([-0., -1.,  1.,  1.,  1., -0., -1., -0., -1.]),
        5,
        1,
        array([-0., -1.,  1.,  1.,  1.,  1., -1., -0., -1.]),
        True],
       [array([0., 0., 0., 0., 0., 0., 0., 0., 0.]),
        4,
        0,
        array([-1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.]),
        False],
       [array([-0., -0., -0., -0., -1., -0., -0., -0., -0.]),
        0,
        0,
        array([ 1., -0., -0., -0., -1., -0., -0., -0., -1.]),
        False],
       [array([-1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.]),
        8,
        0,
        array([-1.,  0., -1.,  0.,  1.,  0.,  0.,  0.,  1.]),
        False],
       [array([ 1., -0., -0., -0., -1., -0., -0., -0., -1.]),
        2,
        0,
        array([ 1., -0.,  1., -1., -1., -0., -0., -0., -1.]),
        False],
       [array([-1.,  0., -1.,  0.,  1.

In [9]:
# 8 2 6 0 7

sample_ans = [{'observation': [0., 0., 0., 0., 0., 0., 0., 0., 0.],
               'action': 8,
               'reward': 0,
               'next_observation': [ 0.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  1.],
               'done': False
              },
              {'observation': [-0., -0., -0., -0., -0., -0., -0., -0., -1.],
               'action': 2,
               'reward': 0,
               'next_observation': ([-0., -0.,  1., -0., -0., -0., -1., -0., -1.]),
               'done': False
              },
              {'observation': ([ 0.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  1.]),
               'action': 6,
               'reward': 0,
               'next_observation': ([-1.,  0., -1.,  0.,  0.,  0.,  1.,  0.,  1.]),
               'done': False
              },
              {'observation': ([-0., -0.,  1., -0., -0., -0., -1., -0., -1.]),
               'action': 0,
               'reward': -1,
               'next_observation': ([ 1., -0.,  1., -0., -0., -0., -1., -1., -1.]),
               'done': True
              },
              {'observation': ([-1.,  0., -1.,  0.,  0.,  0.,  1.,  0.,  1.]),
               'action': 7,
               'reward': 1,
               'next_observation': ([-1.,  0., -1.,  0.,  0.,  0.,  1.,  1.,  1.]),
               'done': True
              }]

sample_ans

[{'observation': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  'action': 8,
  'reward': [0, 0],
  'next_observation': [0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]},
 {'observation': [-0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -1.0],
  'action': 2,
  'reward': [0, 0],
  'next_observation': [-0.0, -0.0, 1.0, -0.0, -0.0, -0.0, -1.0, -0.0, -1.0]},
 {'observation': [0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0],
  'action': 6,
  'reward': [0, 0],
  'next_observation': [-1.0, 0.0, -1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0]},
 {'observation': [-0.0, -0.0, 1.0, -0.0, -0.0, -0.0, -1.0, -0.0, -1.0],
  'action': 0,
  'reward': [-1, 1],
  'next_observation': [1.0, -0.0, 1.0, -0.0, -0.0, -0.0, -1.0, -1.0, -1.0]},
 {'observation': [-1.0, 0.0, -1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
  'action': 7,
  'reward': [1, -1],
  'next_observation': [-1.0, 0.0, -1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0]}]

In [26]:
# 1 4 0 2 6 3 5 7 8

sample = [{'observation': ([0., 0., 0., 0., 0., 0., 0., 0., 0.]),
           'action': 1,
           'reward': 0,
           'next_observation': ([ 0.,  1.,  0.,  0., -1.,  0.,  0.,  0.,  0.])},
          {'observation': ([-0., -1., -0., -0., -0., -0., -0., -0., -0.]),
           'action': 4,
           'reward': 0,
           'next_observation': ([-1., -1., -0., -0.,  1., -0., -0., -0., -0.])},
          {'observation': ([ 0.,  1.,  0.,  0., -1.,  0.,  0.,  0.,  0.]),
           'action': 0,
           'reward': 0,
           'next_observation': ([ 1.,  1., -1.,  0., -1.,  0.,  0.,  0.,  0.])},
          {'observation': ([-1., -1., -0., -0.,  1., -0., -0., -0., -0.]),
           'action': 2,
           'reward': 0,
           'next_observation': ([-1., -1.,  1., -0.,  1., -0., -1., -0., -0.])},
          {'observation': ([ 1.,  1., -1.,  0., -1.,  0.,  0.,  0.,  0.]),
           'action': 6,
           'reward': 0,
           'next_observation': ([ 1.,  1., -1., -1., -1.,  0.,  1.,  0.,  0.])},
          {'observation': ([-1., -1.,  1., -0.,  1., -0., -1., -0., -0.]),
           'action': 3,
           'reward': 0,
           'next_observation': ([-1., -1.,  1.,  1.,  1., -1., -1., -0., -0.])},
          {'observation': ([ 1.,  1., -1., -1., -1.,  0.,  1.,  0.,  0.]),
           'action': 5,
           'reward': 0,
           'next_observation': ([ 1.,  1., -1., -1., -1.,  1.,  1., -1.,  0.])},
          {'observation': ([-1., -1.,  1.,  1.,  1., -1., -1., -0., -0.]),
           'action': 7,
           'reward': 0,
           'next_observation': ([-1., -1.,  1.,  1.,  1., -1., -1.,  1., -1.])},
          {'observation': ([ 1.,  1., -1., -1., -1.,  1.,  1., -1.,  0.]),
           'action': 8,
           'reward': 0,
           'next_observation': ([ 1.,  1., -1., -1., -1.,  1.,  1., -1.,  1.])}]

sample

[{'observation': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  'action': 1,
  'reward': 0,
  'next_observation': [0.0, 1.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0]},
 {'observation': [-0.0, -1.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0],
  'action': 4,
  'reward': 0,
  'next_observation': [-1.0, -1.0, -0.0, -0.0, 1.0, -0.0, -0.0, -0.0, -0.0]},
 {'observation': [0.0, 1.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0],
  'action': 0,
  'reward': 0,
  'next_observation': [1.0, 1.0, -1.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0]},
 {'observation': [-1.0, -1.0, -0.0, -0.0, 1.0, -0.0, -0.0, -0.0, -0.0],
  'action': 2,
  'reward': 0,
  'next_observation': [-1.0, -1.0, 1.0, -0.0, 1.0, -0.0, -1.0, -0.0, -0.0]},
 {'observation': [1.0, 1.0, -1.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0],
  'action': 6,
  'reward': 0,
  'next_observation': [1.0, 1.0, -1.0, -1.0, -1.0, 0.0, 1.0, 0.0, 0.0]},
 {'observation': [-1.0, -1.0, 1.0, -0.0, 1.0, -0.0, -1.0, -0.0, -0.0],
  'action': 3,
  'reward': 0,
  'next_observation': [-1.0, -1.0, 1.0