In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
from py_files.board import Board
from py_files.player import Q_player, Random_player, Human

import numpy as np

Using TensorFlow backend.


In [4]:
p1_config = {'player_type':'human', 'hidden_layers_size':[20,10,30]}
p2_config = {'player_type':'human', 'hidden_layers_size':[20,10,10]}

win_reward = 1
lose_reward = -1
draw_reward = 0

test_board = Board(p1_config=p1_config, p2_config=p2_config, 
                   win_reward=win_reward, lose_reward=lose_reward, 
                   draw_reward=draw_reward)

In [8]:
episode = 1

test_board.train(episode)

Current episode: 0
Pick a cell (top left is 0 and bottom right is 8): 
1
Pick a cell (top left is 0 and bottom right is 8): 
4
Pick a cell (top left is 0 and bottom right is 8): 
0
Pick a cell (top left is 0 and bottom right is 8): 
2
Pick a cell (top left is 0 and bottom right is 8): 
6
Pick a cell (top left is 0 and bottom right is 8): 
3
Pick a cell (top left is 0 and bottom right is 8): 
5
Pick a cell (top left is 0 and bottom right is 8): 
7
Pick a cell (top left is 0 and bottom right is 8): 
8


In [9]:
p1 = test_board.get_player(1)

In [10]:
memory = p1.memory
p1.memory.memory

deque([[array([0., 0., 0., 0., 0., 0., 0., 0., 0.]),
        1,
        0,
        array([ 0.,  1.,  0.,  0., -1.,  0.,  0.,  0.,  0.]),
        False],
       [array([-0., -1., -0., -0., -0., -0., -0., -0., -0.]),
        4,
        0,
        array([-1., -1., -0., -0.,  1., -0., -0., -0., -0.]),
        False],
       [array([ 0.,  1.,  0.,  0., -1.,  0.,  0.,  0.,  0.]),
        0,
        0,
        array([ 1.,  1., -1.,  0., -1.,  0.,  0.,  0.,  0.]),
        False],
       [array([-1., -1., -0., -0.,  1., -0., -0., -0., -0.]),
        2,
        0,
        array([-1., -1.,  1., -0.,  1., -0., -1., -0., -0.]),
        False],
       [array([ 1.,  1., -1.,  0., -1.,  0.,  0.,  0.,  0.]),
        6,
        0,
        array([ 1.,  1., -1., -1., -1.,  0.,  1.,  0.,  0.]),
        False],
       [array([-1., -1.,  1., -0.,  1., -0., -1., -0., -0.]),
        3,
        0,
        array([-1., -1.,  1.,  1.,  1., -1., -1., -0., -0.]),
        False],
       [array([ 1.,  1., -1., -1., -1

In [42]:
train = np.stack(memory.sample(2), axis=1)
train

np.stack(train[1])

array([3, 1])

In [21]:
p1.memory.sample(4)

[{'observation': array([ 0.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  1.]),
  'action': 6,
  'reward': 0,
  'next_observation': array([-1.,  0., -1.,  0.,  0.,  0.,  1.,  0.,  1.])},
 {'observation': array([-0., -0.,  1., -0., -0., -0., -1., -0., -1.]),
  'action': 0,
  'reward': -1,
  'next_observation': array([ 1., -0.,  1., -0., -0., -0., -1., -1., -1.])},
 {'observation': array([-1.,  0., -1.,  0.,  0.,  0.,  1.,  0.,  1.]),
  'action': 7,
  'reward': 1,
  'next_observation': array([-1.,  0., -1.,  0.,  0.,  0.,  1.,  1.,  1.])},
 {'observation': array([0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  'action': 8,
  'reward': 0,
  'next_observation': array([ 0.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  1.])}]

In [9]:
# 8 2 6 0 7

sample_ans = [{'observation': [0., 0., 0., 0., 0., 0., 0., 0., 0.],
               'action': 8,
               'reward': 0,
               'next_observation': [ 0.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  1.],
               'done': False
              },
              {'observation': [-0., -0., -0., -0., -0., -0., -0., -0., -1.],
               'action': 2,
               'reward': 0,
               'next_observation': ([-0., -0.,  1., -0., -0., -0., -1., -0., -1.]),
               'done': False
              },
              {'observation': ([ 0.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  1.]),
               'action': 6,
               'reward': 0,
               'next_observation': ([-1.,  0., -1.,  0.,  0.,  0.,  1.,  0.,  1.]),
               'done': False
              },
              {'observation': ([-0., -0.,  1., -0., -0., -0., -1., -0., -1.]),
               'action': 0,
               'reward': -1,
               'next_observation': ([ 1., -0.,  1., -0., -0., -0., -1., -1., -1.]),
               'done': True
              },
              {'observation': ([-1.,  0., -1.,  0.,  0.,  0.,  1.,  0.,  1.]),
               'action': 7,
               'reward': 1,
               'next_observation': ([-1.,  0., -1.,  0.,  0.,  0.,  1.,  1.,  1.]),
               'done': True
              }]

sample_ans

[{'observation': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  'action': 8,
  'reward': [0, 0],
  'next_observation': [0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]},
 {'observation': [-0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -1.0],
  'action': 2,
  'reward': [0, 0],
  'next_observation': [-0.0, -0.0, 1.0, -0.0, -0.0, -0.0, -1.0, -0.0, -1.0]},
 {'observation': [0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0],
  'action': 6,
  'reward': [0, 0],
  'next_observation': [-1.0, 0.0, -1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0]},
 {'observation': [-0.0, -0.0, 1.0, -0.0, -0.0, -0.0, -1.0, -0.0, -1.0],
  'action': 0,
  'reward': [-1, 1],
  'next_observation': [1.0, -0.0, 1.0, -0.0, -0.0, -0.0, -1.0, -1.0, -1.0]},
 {'observation': [-1.0, 0.0, -1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
  'action': 7,
  'reward': [1, -1],
  'next_observation': [-1.0, 0.0, -1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0]}]

In [26]:
# 1 4 0 2 6 3 5 7 8

sample = [{'observation': ([0., 0., 0., 0., 0., 0., 0., 0., 0.]),
           'action': 1,
           'reward': 0,
           'next_observation': ([ 0.,  1.,  0.,  0., -1.,  0.,  0.,  0.,  0.])},
          {'observation': ([-0., -1., -0., -0., -0., -0., -0., -0., -0.]),
           'action': 4,
           'reward': 0,
           'next_observation': ([-1., -1., -0., -0.,  1., -0., -0., -0., -0.])},
          {'observation': ([ 0.,  1.,  0.,  0., -1.,  0.,  0.,  0.,  0.]),
           'action': 0,
           'reward': 0,
           'next_observation': ([ 1.,  1., -1.,  0., -1.,  0.,  0.,  0.,  0.])},
          {'observation': ([-1., -1., -0., -0.,  1., -0., -0., -0., -0.]),
           'action': 2,
           'reward': 0,
           'next_observation': ([-1., -1.,  1., -0.,  1., -0., -1., -0., -0.])},
          {'observation': ([ 1.,  1., -1.,  0., -1.,  0.,  0.,  0.,  0.]),
           'action': 6,
           'reward': 0,
           'next_observation': ([ 1.,  1., -1., -1., -1.,  0.,  1.,  0.,  0.])},
          {'observation': ([-1., -1.,  1., -0.,  1., -0., -1., -0., -0.]),
           'action': 3,
           'reward': 0,
           'next_observation': ([-1., -1.,  1.,  1.,  1., -1., -1., -0., -0.])},
          {'observation': ([ 1.,  1., -1., -1., -1.,  0.,  1.,  0.,  0.]),
           'action': 5,
           'reward': 0,
           'next_observation': ([ 1.,  1., -1., -1., -1.,  1.,  1., -1.,  0.])},
          {'observation': ([-1., -1.,  1.,  1.,  1., -1., -1., -0., -0.]),
           'action': 7,
           'reward': 0,
           'next_observation': ([-1., -1.,  1.,  1.,  1., -1., -1.,  1., -1.])},
          {'observation': ([ 1.,  1., -1., -1., -1.,  1.,  1., -1.,  0.]),
           'action': 8,
           'reward': 0,
           'next_observation': ([ 1.,  1., -1., -1., -1.,  1.,  1., -1.,  1.])}]

sample

[{'observation': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  'action': 1,
  'reward': 0,
  'next_observation': [0.0, 1.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0]},
 {'observation': [-0.0, -1.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0],
  'action': 4,
  'reward': 0,
  'next_observation': [-1.0, -1.0, -0.0, -0.0, 1.0, -0.0, -0.0, -0.0, -0.0]},
 {'observation': [0.0, 1.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0],
  'action': 0,
  'reward': 0,
  'next_observation': [1.0, 1.0, -1.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0]},
 {'observation': [-1.0, -1.0, -0.0, -0.0, 1.0, -0.0, -0.0, -0.0, -0.0],
  'action': 2,
  'reward': 0,
  'next_observation': [-1.0, -1.0, 1.0, -0.0, 1.0, -0.0, -1.0, -0.0, -0.0]},
 {'observation': [1.0, 1.0, -1.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0],
  'action': 6,
  'reward': 0,
  'next_observation': [1.0, 1.0, -1.0, -1.0, -1.0, 0.0, 1.0, 0.0, 0.0]},
 {'observation': [-1.0, -1.0, 1.0, -0.0, 1.0, -0.0, -1.0, -0.0, -0.0],
  'action': 3,
  'reward': 0,
  'next_observation': [-1.0, -1.0, 1.0